name: skeo
version: 1.0.0
publish_to: none
description: Stream resolver for common hosters, rewritten in Dart for Flutter projects.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  html: ^0.15.6
  http: ^1.2.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.8
